encrypt.key: ${ENCRYPT_KEY}

spring.cloud:
  config:
    server:
      git:
        uri: "${CONFIG_REPO}"
        username: "${CONFIG_USERNAME}"
        password: "${CONFIG_PASSWORD}"
spring.security.user:
  name: ${USERNAME}
  password: ${PASSWORD}
