encrypt.key: ${ENCRYPT_KEY}

spring.cloud:
  config:
    server:
      git:
        uri: "${GIT_REPO}"
        username: "${GIT_USERNAME}"
        password: "${GIT_PASSWORD}"
spring.security.user:
  name: ${USERNAME}
  password: ${PASSWORD}
